### PR TITLE
hackfix for tap to select on mobile devices

### LINKED ISSUE #202: Touch to select/deselect geometries on mobile is not working
A user reported that when loading the app on their tablet, they could draw a polygon to select geometries, but tapping them was not responsive.

This is due to mapbox-gl-draw hijacking events.  This is a documented bug: https://github.com/mapbox/mapbox-gl-draw/issues/617

### PR DESCRIPTION
**Pull request by chriswhong**
This PR adds a workaround that will restore touch to select/deselect polygons on mobile devices.
A bug in `mapbox-gl-draw` causes it to hijack touch events even when the user is not actively drawing.  

The workaround is simply to add the draw control to the map only when the user clicks the draw button, and to remove it when they are done.  Once the bug is fixed we can revert to having the control on all the time.

Closes #202

### CODE REVIEW

File: app/controllers/index.js [hunk 1]
```diff
@@ -98,10 +98,12 @@ export default Ember.Controller.extend({
 
     handleDrawButtonClick() {
       const drawMode = this.get('drawMode');
+      const map = this.get('selection').currentMapInstance;
```
Comment (allthesignals) [inline app/controllers/index.js]: This can be just be `const map = this.get('selection.currentMapInstance');`

File: app/controllers/index.js [hunk 2]
```diff
@@ -132,7 +134,13 @@ export default Ember.Controller.extend({
     handleDrawModeChange(e) {
       const drawMode = e.mode === 'draw_polygon';
       // delay setting drawMode boolean so that polygon-closing click won't be handled
-      setTimeout(() => { this.set('drawMode', drawMode); }, 200);
+      setTimeout(() => {
+        this.set('drawMode', drawMode);
+        if (!drawMode) {
+          const map = this.get('selection').currentMapInstance;
```
Comment (allthesignals) [inline app/controllers/index.js]: ` const map = this.get('selection.currentMapInstance');`
